version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /dizin/data:/var/lib/postgresql/data
    env_file:
      - ./environment/docker.env
    networks:
      - januam-stack

  januam-api:
    container_name: januam-api
    image: januam/januam-api
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    env_file:
      - ./environment/api.dev.env
    networks:
      - januam-stack
    restart: always

  januam-client:
    container_name: januam-client
    image: januam/januam-client
    depends_on:
      - januam-api
    ports:
      - "3000:3000"
    networks:
      - januam-stack
    restart: always

  janaum-nginx:
    container_name: janaum-nginx
    image: januam/janaum-nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
      - januam-api
      - januma-client
    ports:
      - "80:80"
    networks:
      - januam-stack
    restart: always
    
networks:
  januam-stack:
    driver: bridge
