version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
    - ./data/postgres:/data/postgres
    - ./log:/etc/postgresql
    - ./etc:/docker-entrypoint-initdb./
    env_file:
      - ./environment/docker.env
    networks:
      - januam-stack

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
    - ./data/pgadmin:/root/.pgadmin
    env_file:
      - ./environment/docker.env
    networks:
      - januam-stack
  api:
    container_name: api
    build:
      context: ../januam-api
      target: production
    volumes:
      - ../januam-api:/src/app
      - /src/app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
      - pgadmin
    ports:
      - "3001:3001"
    env_file:
      - ./environment/api.dev.env
    networks:
      - januam-stack

  client:
    ports:
      - "3000:3000"
    build:
      context: ../januam-frontend
      dockerfile: Dockerfile
    volumes:
      - ../januam-frontend/:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - januam-stack
    restart: always

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - januam-stack

networks:
  januam-stack:
    driver: bridge
